// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcqxYtgpC5kxt-YnBPzxVOwO3czp_8ZU',
    appId: '1:165801064823:web:c2387cc8a1fddc8d01c972',
    messagingSenderId: '165801064823',
    projectId: 'shoppify-23940',
    authDomain: 'shoppify-23940.firebaseapp.com',
    storageBucket: 'shoppify-23940.appspot.com',
    measurementId: 'G-0BTL0GXT8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzNu6Z1TeFJW1zHGzosu_GZZ7OCY3L9Q',
    appId: '1:165801064823:android:433e7fe9f62237c501c972',
    messagingSenderId: '165801064823',
    projectId: 'shoppify-23940',
    storageBucket: 'shoppify-23940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlO3-ZWc62tvFz6f-7qwHh5FznWilE-Zs',
    appId: '1:165801064823:ios:b1f8177fbe965e3801c972',
    messagingSenderId: '165801064823',
    projectId: 'shoppify-23940',
    storageBucket: 'shoppify-23940.appspot.com',
    iosBundleId: 'com.example.shoppify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlO3-ZWc62tvFz6f-7qwHh5FznWilE-Zs',
    appId: '1:165801064823:ios:b1f8177fbe965e3801c972',
    messagingSenderId: '165801064823',
    projectId: 'shoppify-23940',
    storageBucket: 'shoppify-23940.appspot.com',
    iosBundleId: 'com.example.shoppify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmcqxYtgpC5kxt-YnBPzxVOwO3czp_8ZU',
    appId: '1:165801064823:web:6662bf267371143a01c972',
    messagingSenderId: '165801064823',
    projectId: 'shoppify-23940',
    authDomain: 'shoppify-23940.firebaseapp.com',
    storageBucket: 'shoppify-23940.appspot.com',
    measurementId: 'G-QP3NT014P2',
  );
}
